// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MikroTikVoucherPrinter.Infrastructure.Data;

#nullable disable

namespace MikroTikVoucherPrinter.Infrastructure.Migrations
{
    [DbContext(typeof(LuxCardDbContext))]
    [Migration("20260714073951_AddVoucherCompositeIndexes")]
    partial class AddVoucherCompositeIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RouterId");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RouterId");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.LuxTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundColorHex")
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImagePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("BackgroundType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("CardHeightMm")
                        .HasColumnType("REAL");

                    b.Property<float>("CardWidthMm")
                        .HasColumnType("REAL");

                    b.Property<int>("CardsPerColumn")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CardsPerRow")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Category")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ElementsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("HorizontalGapMm")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LinkedProfileName")
                        .HasColumnType("TEXT");

                    b.Property<float>("MarginBottomMm")
                        .HasColumnType("REAL");

                    b.Property<float>("MarginLeftMm")
                        .HasColumnType("REAL");

                    b.Property<float>("MarginRightMm")
                        .HasColumnType("REAL");

                    b.Property<float>("MarginTopMm")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Orientation")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OutputType")
                        .HasColumnType("INTEGER");

                    b.Property<float>("PageHeightMm")
                        .HasColumnType("REAL");

                    b.Property<float>("PageWidthMm")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.Property<float>("VerticalGapMm")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Category");

                    b.HasIndex("RouterId");

                    b.ToTable("LuxTemplates");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.PrintJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CardCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CurrentStep")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("JobParametersJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobVersion")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OutputFilePath")
                        .HasColumnType("TEXT");

                    b.Property<int>("OutputFormat")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PdfCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("PrintedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrintedCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReservedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SyncedCount")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemplateVersion")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("BatchId");

                    b.HasIndex("RouterId");

                    b.ToTable("PrintJobs", (string)null);
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.PrintJobEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Details")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("JobId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.HasIndex("RouterId");

                    b.ToTable("PrintJobEvents", (string)null);
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("MikroTikProfileId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("RateLimit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RouterHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedUsers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SystemType")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transfer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uptime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RouterId");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Name", "RouterHost")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.TemplateConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImagePath")
                        .HasColumnType("TEXT");

                    b.Property<float>("BarcodeSize")
                        .HasColumnType("REAL");

                    b.Property<float>("BarcodeX")
                        .HasColumnType("REAL");

                    b.Property<float>("BarcodeY")
                        .HasColumnType("REAL");

                    b.Property<float>("CardHeight")
                        .HasColumnType("REAL");

                    b.Property<float>("CardWidth")
                        .HasColumnType("REAL");

                    b.Property<int>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FontColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FontFamily")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("FontSize")
                        .HasColumnType("REAL");

                    b.Property<string>("FrameColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("FrameSize")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsBold")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsItalic")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSystemTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kind")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LegacyRendererKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("LinkedProfileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoImagePath")
                        .HasColumnType("TEXT");

                    b.Property<float>("MarginX")
                        .HasColumnType("REAL");

                    b.Property<float>("MarginY")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PasswordX")
                        .HasColumnType("REAL");

                    b.Property<float>("PasswordY")
                        .HasColumnType("REAL");

                    b.Property<float>("PriceX")
                        .HasColumnType("REAL");

                    b.Property<float>("PriceY")
                        .HasColumnType("REAL");

                    b.Property<float>("PrintDateX")
                        .HasColumnType("REAL");

                    b.Property<float>("PrintDateY")
                        .HasColumnType("REAL");

                    b.Property<float>("QrSize")
                        .HasColumnType("REAL");

                    b.Property<float>("QrX")
                        .HasColumnType("REAL");

                    b.Property<float>("QrY")
                        .HasColumnType("REAL");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<float>("SerialNumberX")
                        .HasColumnType("REAL");

                    b.Property<float>("SerialNumberY")
                        .HasColumnType("REAL");

                    b.Property<bool>("ShowBarcode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPassword")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPrice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPrintDate")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowQr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowSerialNumber")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowTime")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowUsername")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowValidity")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("ThermalPrintableWidthMm")
                        .HasColumnType("REAL");

                    b.Property<float>("TimeX")
                        .HasColumnType("REAL");

                    b.Property<float>("TimeY")
                        .HasColumnType("REAL");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("UsernameX")
                        .HasColumnType("REAL");

                    b.Property<float>("UsernameY")
                        .HasColumnType("REAL");

                    b.Property<float>("ValidityX")
                        .HasColumnType("REAL");

                    b.Property<float>("ValidityY")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("RouterId");

                    b.ToTable("TemplateConfigs");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<long>("BytesUsed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("TEXT");

                    b.Property<int>("CredentialMode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("DeletedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DeletedSource")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DownloadUsedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("ImportDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MikroTikUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<int>("PrintStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RouterId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncError")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("UploadUsedBytes")
                        .HasColumnType("INTEGER");

                    b.Property<long>("UptimeUsedSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("VoucherSource")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("RouterId");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("VoucherSource");

                    b.HasIndex("Username", "RouterId")
                        .IsUnique();

                    b.HasIndex("RouterId", "IsDeleted", "CreatedAt");

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.PrintJob", b =>
                {
                    b.HasOne("MikroTikVoucherPrinter.Domain.Entities.Batch", "Batch")
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.PrintJobEvent", b =>
                {
                    b.HasOne("MikroTikVoucherPrinter.Domain.Entities.PrintJob", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Job");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Profile", b =>
                {
                    b.HasOne("MikroTikVoucherPrinter.Domain.Entities.TemplateConfig", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Voucher", b =>
                {
                    b.HasOne("MikroTikVoucherPrinter.Domain.Entities.Agent", "Agent")
                        .WithMany("Vouchers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MikroTikVoucherPrinter.Domain.Entities.Batch", "Batch")
                        .WithMany("Vouchers")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Batch", b =>
                {
                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
