// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MikroTikVoucherPrinter.Infrastructure.Data;

#nullable disable

namespace MikroTikVoucherPrinter.Infrastructure.Migrations
{
    [DbContext(typeof(LuxCardDbContext))]
    [Migration("20260429230432_AddPrintTemplateSystem")]
    partial class AddPrintTemplateSystem
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Balance")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("CommissionRate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Agents");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Batch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("TotalCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Batches");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Profile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("RateLimit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RouterHost")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SharedUsers")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("TemplateId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Transfer")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Uptime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.HasIndex("Name", "RouterHost")
                        .IsUnique();

                    b.ToTable("Profiles");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.TemplateConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("BackgroundImagePath")
                        .HasColumnType("TEXT");

                    b.Property<float>("CardHeight")
                        .HasColumnType("REAL");

                    b.Property<float>("CardWidth")
                        .HasColumnType("REAL");

                    b.Property<int>("Columns")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FontColorHex")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("FontSize")
                        .HasColumnType("REAL");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("PasswordX")
                        .HasColumnType("REAL");

                    b.Property<float>("PasswordY")
                        .HasColumnType("REAL");

                    b.Property<float>("PriceX")
                        .HasColumnType("REAL");

                    b.Property<float>("PriceY")
                        .HasColumnType("REAL");

                    b.Property<float>("QrSize")
                        .HasColumnType("REAL");

                    b.Property<float>("QrX")
                        .HasColumnType("REAL");

                    b.Property<float>("QrY")
                        .HasColumnType("REAL");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Rows")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPassword")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowPrice")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowQr")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ShowUsername")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<float>("UsernameX")
                        .HasColumnType("REAL");

                    b.Property<float>("UsernameY")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.ToTable("TemplateConfigs");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Voucher", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("AgentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("CredentialMode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MikroTikUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SyncError")
                        .HasColumnType("TEXT");

                    b.Property<int>("SyncStatus")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("SyncedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AgentId");

                    b.HasIndex("BatchId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("SyncStatus");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Vouchers");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Profile", b =>
                {
                    b.HasOne("MikroTikVoucherPrinter.Domain.Entities.TemplateConfig", "Template")
                        .WithMany()
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Template");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Voucher", b =>
                {
                    b.HasOne("MikroTikVoucherPrinter.Domain.Entities.Agent", "Agent")
                        .WithMany("Vouchers")
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MikroTikVoucherPrinter.Domain.Entities.Batch", "Batch")
                        .WithMany("Vouchers")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agent");

                    b.Navigation("Batch");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Agent", b =>
                {
                    b.Navigation("Vouchers");
                });

            modelBuilder.Entity("MikroTikVoucherPrinter.Domain.Entities.Batch", b =>
                {
                    b.Navigation("Vouchers");
                });
#pragma warning restore 612, 618
        }
    }
}
